### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by yesyestoday2020** [imfunniee/gitfolio#103]
click button 'Create blog'

<img width="780" alt="截屏2020-01-0603 15 44" src="https://user-images.githubusercontent.com/35359288/71784839-127f0100-3033-11ea-8f32-8585a7e13be9.png">

Error
<img width="1137" alt="截屏2020-01-0603 13 05" src="https://user-images.githubusercontent.com/35359288/71784853-3e9a8200-3033-11ea-831d-6259d94dfedc.png">

**Comment by jeev20** [comment]
I experienced the same bug today. 
![Error](https://user-images.githubusercontent.com/19647823/77484493-f701e600-6e2a-11ea-9404-87842e0f4ab3.PNG)

By the way, thank you for the wonderful tool. This project is amazing @imfunniee. Stared!

**Comment by johnathan-codes** [comment]
Might be same problem as in #90

**Comment by jeev20** [comment]
> Might be same problem as in #90

The solution in #90 worked. 
**_Solution: Add a background image when writing a blog._**
 If no image is provided the _"Cannot read property 'split' of undefined"_ error is observed.
