### ISSUE TITLE
An all blog version of this

### ISSUE THREAD

**Issue by stephenajulu** [imfunniee/gitfolio#106]
# What feature should be added?

Kindly make an all blog version of this theme.

# Why should this feature be added?

Because this theme is awesome especially for portfolios and blogs. The deep blacks, the card design, all of it is amazing not forgetting it can easily be turned into a PWA. It's fast. Has it's own mini CMS.

**Comment by BeyondMagic** [comment]
This.
I really loved the blog part, for me, it could be the main part of the project.

**Comment by BeyondMagic** [comment]
@stephenajulu I've found [this repository](https://github.com/NevenLeung/write-down), looks really good.

**Comment by imfunniee** [comment]
working on it, prob release it by next month

**Comment by stephenajulu** [comment]
Great @imfunniee Thank you very much

**Comment by owlsecco** [comment]
Hey, is it ready? The all blog version?
