### ISSUE TITLE
Limit the number of repository

### ISSUE THREAD

**Issue by haoict** [imfunniee/gitfolio#110]
# What feature should be added?

Limit the number of repository to show only few highlighted repositories. 

The number can be inputted by user.

# Why should this feature be added?

I don't want the page too long. I only want to display some highlighted repositories.

**Comment by mdminhazulhaque** [comment]
This may help you. Already submitted PR 2 months ago.

https://github.com/imfunniee/gitfolio/pull/111

**Comment by haoict** [comment]
@mdminhazulhaque 
Thanks. But the owner doesn't seem to care about his product anymore
