### ISSUE TITLE
Cannot create blog - gitfolio-0.1.5

### ISSUE THREAD

**Issue by shaktiug** [imfunniee/gitfolio#113]
gitfolio-0.1.5

I have tried this code on node version 12.16.3 and 10.14 however it doesnt work for me when i click on create blog.

The below error occurs on the terminal :-
C:\gitfolio-0.1.5>gitfolio ui

Starting...
The GUI is running on port 3000, Navigate to http://localhost:3000 in your browser

TypeError: Cannot read property 'split' of undefined
    at C:\Users\shasingh33\AppData\Roaming\npm\node_modules\gitfolio\ui.js:71:35

**Comment by shaktiug** [comment]
Any update. Can you fix that ?

**Comment by Dawoox** [comment]
Error appears when no background image is given for the blog. #90
