### ISSUE TITLE
Blogs not showing up on the main page

### ISSUE THREAD

**Issue by Dawoox** [imfunniee/gitfolio#118]
<details>
<summary>System Information</summary>

| Name            | Value                                                          |
| --------------- | -------------------------------------------------------------- |
| OS              | Windows 10 Build 18363.1316                                          |
| Node Version    | v14.15.1                           |
| Project Version | 0.1.5 |

</details>

<details>
<summary>What is the current behavior?</summary>
<br>
When you create an article, everything seems to work, no errors appear on the console, the article is correctly generated with its folder, its images, and its index.html works, but on the home page no tile is created to link to this article as shown on the demo site.
</details>

<details>
<summary>What is the expected behavior?</summary>
<br>
On the home page a tile should be generated to link to the article newly created.
On the demo site the blog tile looks like this (The screenshot is at the very end because I can't manage to include it here 🤔 )
</details>

<details>
<summary>Logs</summary>
<br>
No revelant logs :/

</details>

I'm pretty sure i'm miss understanding something on how to get the blog system working but i can't find any help other than that so sorry if the anwser is pretty obvious.

![Screenshot_32](https://user-images.githubusercontent.com/48325941/106323653-0b4b1680-6278-11eb-8b13-117118885689.png)

**Comment by Dawoox** [comment]
Update : It's not showing up when I test it on localhost, but it's working fine when I push it to my repo 🤔

**Comment by DhruvDoshi** [comment]
This is the problem with the building in Javascript
