### ISSUE TITLE
Subsequent builds fail with: undefined:1

### ISSUE THREAD

**Issue by furriephillips** [imfunniee/gitfolio#12]
I followed the steps in the README.md and performed an initial build, to see it it worked - then on subsequent tries (to alter the theme and background), I received the error: -

```
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /home/myuser/gitfolio/update.js:6:17
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```
I managed to figure out that if I reset the config.json before rebuilding, subsequent [re]builds work: -
`git checkout -- config.json`

**Comment by imfunniee** [comment]
does it work?

**Comment by SyeedHasan** [comment]
The error still persists for me
