### ISSUE TITLE
Readme confusion

### ISSUE THREAD

**Issue by hamogor** [imfunniee/gitfolio#15]
> To run your website open index.html or simply type index.html and hit enter in your terminal.

Typing index.html and hitting enter? What?

**Comment by 1RedOne** [comment]
Typing in a web page into most terminals and hitting enter it will open in the default browser of choice.

**Comment by jakehamilton** [comment]
@1RedOne, I've never had that be the case. Should we rather recommend something like `open` and `xdg-open`?

**Comment by hamogor** [comment]
Or even just: navigate to index.html in your browser.
