### ISSUE TITLE
'Work' not sorted, repo with 1 stars gets on top

### ISSUE THREAD

**Issue by surajmandalcell** [imfunniee/gitfolio#18]
Shouldn't 'Work' be sorted by number of stars to show best work first?

**Comment by alexis-coulombe** [comment]
Idk for now, but i did a merge request. It will add filtering by date, name, stars and forks.

**Comment by imfunniee** [comment]
ye it filters by date for now not stars

**Comment by DonIsaac** [comment]
I don't believe there is a way in the github API to sort by stars without doing it by hand.

https://developer.github.com/v3/repos/#list-user-repositories

**Comment by imfunniee** [comment]
you need to push all the repos data to an array and then sort the array according to stars

**Comment by lonePatient** [comment]
in `populate.js` file
```text
function sortStart(a,b){  
  return b.stargazers_count-a.stargazers_count
}

module.exports.updateHTML = (username) => {
//add data to assets/index.html
jsdom.fromFile("./assets/index.html", options).then(function (dom) {
    let window = dom.window, document = window.document;
    (async () => {
        try {
            console.log("Building HTML/CSS...");
            var repos = await got(`https://api.github.com/users/${username}/repos?sort=created`);
            repos = JSON.parse(repos.body);
            repos.sort(sortStart);
```

**Comment by imfunniee** [comment]
@Chargnn is already working on it

**Comment by imfunniee** [comment]
you can now sort repos according to stars

```sh
node build --name username --sort star --order desc
```
