### ISSUE TITLE
username not found in config.json

### ISSUE THREAD

**Issue by viniciusmoreria** [imfunniee/gitfolio#19]
I am quite new to this, what am I doing wrong?

i did run the node build --name myusername

**Comment by jakehamilton** [comment]
Was this the command you ran?

```
node build --name viniciusmoreeira
```

EDIT: Also it may be useful for you to paste the output of the build.

**Comment by viniciusmoreria** [comment]
Yes it was.

But when i open the index.html that was generated theres just the title Work and the phrase made by a human on earth.

**Comment by viniciusmoreria** [comment]
{ HTTPError: Response code 404 (Not Found)
    at EventEmitter.emitter.on (C:\Users\vinic\Desktop\gitfolio\node_modules\got\source\as-promise.js:74:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'HTTPError',
  host: 'api.github.com',
  hostname: 'api.github.com',
  method: 'GET',
  path: '/users/viniciusmoreeira--dark/repos?sort=created',

**Comment by jakehamilton** [comment]
I have a feeling that there may have been a typo in the command you ran given this line:

```
path: '/users/viniciusmoreeira--dark/repos?sort=created'
```

Can you try running this command?

```
node build --dark --name viniciusmoreeira 
```

**Comment by viniciusmoreria** [comment]
Well, i feel quite dumb now,

I was just trying to type like in the readme:

$ node build --name username --dark

It worked, thank you!

**Comment by jakehamilton** [comment]
No worries, glad it was fixed!
