### ISSUE TITLE
GitHub emoji in description

### ISSUE THREAD

**Issue by jfeigel** [imfunniee/gitfolio#2]
Can you render the GitHub emoji in the description of the repo?

gitfolio
![gitfolio](https://user-images.githubusercontent.com/4389385/57462671-ebbbc100-723e-11e9-8b6f-491ae87ddf1d.png)

GitHub
![github](https://user-images.githubusercontent.com/4389385/57462677-ed858480-723e-11e9-9053-e5be447e73f3.png)

**Comment by imfunniee** [comment]
ok

**Comment by imfunniee** [comment]
done 👀🙌👌🔥
