### ISSUE TITLE
Show pinned repositories and sort by them

### ISSUE THREAD

**Issue by shyim** [imfunniee/gitfolio#26]
Maybe pinned repositories should be shown 🤔

**Comment by imfunniee** [comment]
so umm... i was going to use this one but there isn't a way to figure out which repositories are pinned and which aren't through github's api unless the user specific the pinned repositories's name or id.

**Comment by shyim** [comment]
Foo is only accessible using GraphQL API and this requires authentication 🙈

**Comment by imfunniee** [comment]
yes, but would you let a random guy access your info 👀
