### ISSUE TITLE
[Idea] Wrap all the commands in CLI

### ISSUE THREAD

**Issue by rohit-gohri** [imfunniee/gitfolio#27]
A simple CLI using something like [commander](https://www.npmjs.com/package/commander) or any other argv parser ([yargs](https://www.npmjs.com/package/yargs)?).
This could have the `build`, `blog`, `update` commands.

Then this could be published to npm too, and one would be able to run it as:
`npx gitfolio build --username xxx`

I could open a basic PR if this seems like a good idea.

**Comment by imfunniee** [comment]
hmm seems like a good idea 😋, create a PR to `cli_feature` branch

```
npm -g gitfolio
gitfolio build --name username
```

**Comment by rohit-gohri** [comment]
Some things to keep in mind before publishing, update package.json with
- repo information
- homepage and bugs urls
- keywords
- change license to same in repo
- maybe add email to author field?

More info can be found at https://docs.npmjs.com/files/package.json

**Comment by imfunniee** [comment]
cool thx @rohit-smpx
