### ISSUE TITLE
Request: Easier blog customization from console

### ISSUE THREAD

**Issue by benstigsen** [imfunniee/gitfolio#3]
So currently blogs are created like so:
`node blog --title my-first-blog`

This however seems misleading, because when you open up the page created, both the tab title and the blog title hasn't been changed.

It would be nice if something like this could be created:
`node blog --title "Some Title Here" --subtitle "Some subtitle here" --folder some-folder-title --pagetitle "Title in tab!"`

`--folder` and `--pagetitle` should be optional, if it hasn't been specified, it should use the `--title` for the tab, and replace whitespace with hyphens for the folder.

Then in the actual `blog.js` file it would simply be something like:
```javascript
document.getElementsByTagName("title")[0].textContent = pagetitle;
document.getElementsByTagName("blog_title")[0].textContent = title;
document.getElementsByTagName("blog_sub_title")[0].textContent = subtitle;
```

I could send a pull requests with changes made to `blog.js` if you'd want that.

**Comment by imfunniee** [comment]
seems like a good idea 👌

**Comment by BenTearzz** [comment]
So apparently anything that has to do with pushing to your directory is broken for me. So here it is: f95099b72d5b968a278d3832d9db59019e1b3489

**Comment by benstigsen** [comment]
This has now been added as a pull request: https://github.com/imfunniee/gitfolio/pull/5
