### ISSUE TITLE
More repositories

### ISSUE THREAD

**Issue by gillesheinesch** [imfunniee/gitfolio#32]
Hi :) 

It would be cool if not only the repositories created by the user would be listed but also the repos where you contributed. 

Would be a nice feature! 

Thanks!

**Comment by Eurus-Holmes** [comment]
agree!

**Comment by AutoVR** [comment]
It would be nice feature

**Comment by rednafi** [comment]
This would be a nice feature. I have contributed to several open source projects and I'd very much like them to appear in my portfolio. Thank you for your amazing work!!

**Comment by gillesheinesch** [comment]
How long does it take that you answer on emails? @imfunniee

**Comment by rohit-gohri** [comment]
I think this could simply be done by adding a [`type=all` param](https://developer.github.com/v3/repos/#list-user-repositories) to the api request here: https://github.com/imfunniee/gitfolio/blob/5d9d2bbba2916bc9f99a090adc52ed80ab02452d/populate.js#L42 and here https://github.com/imfunniee/gitfolio/blob/5d9d2bbba2916bc9f99a090adc52ed80ab02452d/populate.js#L57

Then if we want to separate contributions we could then filter the repos by owner

**Comment by rohit-gohri** [comment]
> Then if we want to separate contributions we could then filter the repos by owner

Or we could get them separately with `type=owner` and `type=member`

**Comment by imfunniee** [comment]
@Monkeyyy11 haven't checked emails in a week.

**Comment by rohit-gohri** [comment]
> I think this could simply be done by adding a [`type=all` param](https://developer.github.com/v3/repos/#list-user-repositories) to the api request here:

Just checked, this will fix #46 (i.e. show org repos you are a member of) but won't give you repos that you have contributed to.
