### ISSUE TITLE
Repo Classification

### ISSUE THREAD

**Issue by Eurus-Holmes** [imfunniee/gitfolio#33]
# What feature should be added?
Repositories classification feature could be added, such as "research", "course project", "engineering project" and so on...

# Why should this feature be added?

It didn't show all mine repositories, and "work" didn't represent the feature of the repositories, so I suggest the repo classification features could be added.

**Comment by Eurus-Holmes** [comment]
Actually, it only showed 4 repositories when I built my gitfolio...

**Comment by imfunniee** [comment]
Why not add it in the description of a repository like "[research]"? Not saying its a bad idea but a user would have to define/classify each repository and then it could be build into a website. 
Seems like a longer process then just defining them in the repository's description.

and the reason it shows only 4 repositories is cause it doesn't show forked one's (working on sorting forks too).

**Comment by Eurus-Holmes** [comment]
but I have more than 4 repositories of my own...

**Comment by Eurus-Holmes** [comment]
As for repo classification, I mean now that it's a personal website, why not choose by users to show own repositories sorted by repo classification, like as the resume showed :)

**Comment by imfunniee** [comment]
You can choose to add or delete stuff from the `index.html` file, its your personal website make it yours by adding stuff to it. This repo just provides you the bare bones of getting started with a "personal website" for everyone 😃

btw that's an issue if it only shows 4 repositories. i figured out the reason behind it. i just need to add `?per_page=1000` to the api call. will fix this soon.

**Comment by Eurus-Holmes** [comment]
thank you~
