### ISSUE TITLE
Overpass the 30 repositories limit

### ISSUE THREAD

**Issue by Kerumen** [imfunniee/gitfolio#34]
The GitHub API limit every endpoints to 30 results ([source](https://developer.github.com/v3/#pagination)). For a user with more than 30 repositories this is a problem as only part of his work is shown.

A temporary workaround would be to add the `per_page` query param to a higher number to get all the repos of the user.

The definitive fix would be to request several times the API as explained [in the docs](https://developer.github.com/v3/guides/traversing-with-pagination/).

**Comment by imfunniee** [comment]
did that in new version v0.1.2, check it out its live 🎉🙌
