### ISSUE TITLE
Can't build, unexepected end of JSON

### ISSUE THREAD

**Issue by lamarios** [imfunniee/gitfolio#35]
<details>
<summary>System Information</summary>

| Name            | Value                                                          |
| --------------- | -------------------------------------------------------------- |
| OS              |  Arch linux                                          |
| Node Version    | 11.15.0                       |
| Project Version |  0.1.1 |

</details>

<details>
<summary>What is the current behavior?</summary>
running build command worked once but doesn't work anymore ?
</details>

<details>
<summary>What is the expected behavior?</summary>
Being able t obuild
</details>

<details>
<summary>Logs</summary>

```
node build --name lamarios
Building HTML/CSS...
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /mnt/services/docker/gitfolio/data/build.js:39:29
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)
```

</details>

**Comment by imfunniee** [comment]
Just released a new version, can you clone that and try again. lemme know if it works 😅

**Comment by Eurus-Holmes** [comment]
@imfunniee I have tried again, but this bug still exists, it occurred after I have built once.

![屏幕快照 2019-05-20 下午7 24 01](https://user-images.githubusercontent.com/34226570/58018412-4c97a300-7b35-11e9-92a7-1d7d4ddbb540.png)

**Comment by abidgulshahid** [comment]
Same Error As @Eurus-Holmes

**Comment by imfunniee** [comment]
so umm looks like when you used update it would clear out config.json file, reason being i was updating the html with only one argument and it needed 4 lol mb
