### ISSUE TITLE
Long repo titles don't fit in boxes, spills out

### ISSUE THREAD

**Issue by zbrasseaux** [imfunniee/gitfolio#41]
<details>
<summary>System Information</summary>

| Name            | Value                                                          |
| --------------- | -------------------------------------------------------------- |
| OS              | Linux                                              |
| Node Version    | 10.10.0                           |
| Project Version | d84d6fd |

</details>

<details>
<summary>Like i mentioned in the titles, long repo titles spill out</summary>

see here for example https://imgur.com/LwI2AKE
</details>

**Comment by zbrasseaux** [comment]
As an aside, I am planning on trying  to fix this myself (probably just some CSS calculations), just wanted you to be aware of it

**Comment by jakehamilton** [comment]
Hmm, options are probably either change wrapping or truncate the text.

I think letting the text wrap should be an easy, workable solution.

**Comment by zbrasseaux** [comment]
wait, am i just stupid? should I be manually creating a new line instead?

**Comment by jakehamilton** [comment]
No, you're doing things right! I'm suggesting solutions for this bug fix. It is a problem that even the demo site has.

**Comment by imfunniee** [comment]
oh wait wth changed the css lol, wait a min lemme fix that real quick
