### ISSUE TITLE
Org repos

### ISSUE THREAD

**Issue by RWOverdijk** [imfunniee/gitfolio#46]
# What feature should be added?

The possibility to list repositories that are part of an organisation.

# Why should this feature be added?

I've put pretty much all of my repos under an org with at least two people per repository allowed to write to them in case I for some reason become unable to tend to them (because it's stuff used in production).

These are still my projects and I would like to be able to add them. If this is already possible and I'm just blind, I do apologise.

**Comment by gillesheinesch** [comment]
Connected to #32

**Comment by RWOverdijk** [comment]
@Monkeyyy11 You're right. Maybe a configurable ownership/contributions divide would be nice.

**Comment by imfunniee** [comment]
working on it 👍
