### ISSUE TITLE
Profile image displaying wrong on mobile

### ISSUE THREAD

**Issue by Gelbpunkt** [imfunniee/gitfolio#49]
<details>
<summary>System Information</summary>

| Name            | Value                                                          |
| --------------- | -------------------------------------------------------------- |
| OS              | Linux (Fedora 30)                                             |
| Node Version    | v10.15.3                           |
| Project Version | cloned this afternoon |

</details>

<details>
<summary>What is the current behavior?</summary>

The profile image displays wrong on my Android 7.1 device. I get the same result in Chrome 74 and Firefox 66, displays correct with Chrome on PC.
https://i.imgur.com/WX6vVBh.png (screenshot with Chrome)
</details>

<details>
<summary>What is the expected behavior?</summary>

The display is correct on your example. (A square)
https://i.imgur.com/WkGL25k.png.

PS: (seems too easy to make a new issue) Can you make the person link actually a hyperlink? :)
</details>

<details>
<summary>Logs</summary>

```
none relevant
```

</details>

**Comment by imfunniee** [comment]
fixed it 😄👍

**Comment by rohit-gohri** [comment]
I think you accidentally committed the file in root of repo instead of `assets` folder in 9c5655ea

**Comment by imfunniee** [comment]
lmao 🤣, fixed it.

**Comment by rohit-gohri** [comment]
> lmao 🤣, fixed it.

Sorry to point out another mistake, but I think you undid the css changes of https://github.com/imfunniee/gitfolio/commit/396817fa in https://github.com/imfunniee/gitfolio/commit/c772b6b4. Unless that was intentional, then ignore.

**Comment by Gelbpunkt** [comment]
^ confirmed :) [This](https://adrian.is-the.best) displays wrong "again" after updating to v0.1.4

**Comment by imfunniee** [comment]
@rohit-smpx reverted them in #71 
@Gelbpunkt umm i think it will update, when i release a new version of it.

**Comment by Gelbpunkt** [comment]
Oh right :blush:Thank you!
