### ISSUE TITLE
How can I solve the problem of "Invalid regular expression flags"?

### ISSUE THREAD

**Issue by Krokette29** [imfunniee/gitfolio#52]
I have just `npm i`, and I met the problem when I typed in `node build --name blabla`, it just said that "SyntaxError: Invalid regular expression flags".  It turns out at the line `if (text.match(/(?<=:\s*).*?(?=\s*:)/gs) != null) {` has a trouble. What happens? My OS is Windows10. Thanks a lot!

**Comment by imfunniee** [comment]
what's your node version?

**Comment by blesson3** [comment]
Duplicate https://github.com/imfunniee/gitfolio/issues/20
