### ISSUE TITLE
Add a linter and lint config

### ISSUE THREAD

**Issue by rohit-gohri** [imfunniee/gitfolio#53]
As the project grows, it would be easier to contribute if the project follows a specific javascript style guide.
These are what I use in my personal projects:
Linter: https://github.com/eslint/eslint
Config: https://www.npmjs.com/package/eslint-config-airbnb

But any other would work too

**Comment by luctst** [comment]
Maybe Prettier too ?

**Comment by imfunniee** [comment]
prettier added 🙌, lint soon
