### ISSUE TITLE
Consider making this a Saber theme?

### ISSUE THREAD

**Issue by egoist** [imfunniee/gitfolio#57]
Hi, this project is a great idea, but I think it can be even better.

# What feature should be added?

Extracting the core features as a [Saber theme](https://saber.land/tutorial/tutorial.html#creating-a-theme), and let the gitfolio CLI generate a starter project.

# Why should this feature be added?

Saber (https://saber.land) is a static website generator built on the top of modern web techs like webpack and Vue.js. Saber generates a modern, performant website with best practices baked in.

You might also know Gatsby.js and VuePress, but Saber is much easier to get started with and it has first-class support for blogging and i18n.

By using Saber, there will be:

- No jQuery.
- No JSDOM, You don't need JSDOM to render static HTML, the app will be statically rendered by default, when the app is loaded in browser the client-side JavaScript will take over it. (Universal website)
- Better development experience. You can preview your website locally, with hot reloading, source mapping support.
- You get more powerful blogging features, enjoy all Markdown features, and you can even use Vue / JavaScript directly in your markdown code.
- Extensibility, Saber is powered by plugins, there're plugins for generating RSS feed, supporting PWA etc.

# How does it look like?

Create a new website:

```bash
gitfolio new my-site
```

This command will ask a few questions, like your GitHub username, then it creates a new folder at `my-site`, in `my-site/saber-config.yml` it looks like:

```yml
# theme can be loaded from local directory of npm package
# in this case it uses `saber-theme-gitfolio`
theme: gitfolio

# Configure here instead of using CLI flags
themeConfig:
  github: username
  theme: dark
```

And `package.json`:

```json
{
  "scripts": {
    "build": "saber build",
    "dev": "saber"
  }
}
```

Build the website:

```bash
npm run build
# Build to ./public
```

Preview locally:

```bash
npm run dev
```

---

A few websites that are built with Saber:

- My blog: https://egoist.moe ([config file](https://github.com/egoist/blog/blob/master/saber-config.js))
- Saber's offical website: https://saber.land
- https://www.h404bi.com ([config file](https://github.com/h404bi/www.h404bi.com/blob/master/saber-config.js))

---

Feel free to close this if you're not interested.

**Comment by imfunniee** [comment]
nope

**Comment by egoist** [comment]
For whoever is interested, I just made it:

https://github.com/saberland/create-portfolio
