### ISSUE TITLE
rendering projects in sorted order 

### ISSUE THREAD

**Issue by abhijithvijayan** [imfunniee/gitfolio#68]
The projects are sorted but still rendered top-bottom approach.
Won't it look better like this?
![Screenshot from 2019-06-01 17-14-28](https://user-images.githubusercontent.com/34790378/58748075-4b4d6b00-8491-11e9-99dc-bede6ebc5003.png)
![Screenshot from 2019-06-01 17-14-43](https://user-images.githubusercontent.com/34790378/58748076-4be60180-8491-11e9-9696-0848722b55c1.png)
![Screenshot from 2019-06-01 17-14-54](https://user-images.githubusercontent.com/34790378/58748077-4be60180-8491-11e9-933c-63d8a0caf512.png)
![Screenshot from 2019-06-01 17-15-10](https://user-images.githubusercontent.com/34790378/58748078-4be60180-8491-11e9-8af6-de4f52419aeb.png)

I can submit a PR if needed.

**Comment by bcliden** [comment]
This should be fixed as of the latest build (from PR #66 ). The live version I believe you're looking at hasn't been updated. Here's an example screenshot of @imfunniee  's latest gitfolio I generated locally:
![latest_ordering_gitfolio](https://user-images.githubusercontent.com/27828594/58749231-70ba8480-8451-11e9-92b4-6fe010896c0e.png)

**Comment by imfunniee** [comment]
ye i would update it once i have more features

**Comment by imfunniee** [comment]
fixed in PR #66
