### ISSUE TITLE
Pages website shows only the README.md file 

### ISSUE THREAD

**Issue by mattbhenley** [imfunniee/gitfolio#7]
I follow the basic instructions. Everything looks successful. When I run `index.html` in my browser, I only see "Work." in plain text. I save the repo and publish the page, only to see the readme.md file. Any help is appreciated!

**Comment by benstigsen** [comment]
Did you remember to build it?
`node build --name mattbhenley`

**Comment by mattbhenley** [comment]
I did. I tried it multiple times with the same result. Just wondering if anyone saw the same, I plan to try it fresh sometime this afternoon.

**Comment by imfunniee** [comment]
can you send a screenshot of what you are seeing?

**Comment by mattbhenley** [comment]
I tried it again, today and it worked perfectly. I can't figure out why it was failing but must've been my error. Thank you for the feedback!
