### ISSUE TITLE
Weird look on mobile

### ISSUE THREAD

**Issue by Gelbpunkt** [imfunniee/gitfolio#76]
<details>
<summary>System Information</summary>

| Name            | Value                                                          |
| --------------- | -------------------------------------------------------------- |
| OS              | Fedora 30/Android                                              |
| Node Version    | 10.16.0                           |
| Project Version | 0.1.5 (latest commit as of this issue) |

</details>

<details>
<summary>What is the current behavior?</summary>

![Screenshot_20190620-153624](https://user-images.githubusercontent.com/38864617/59853630-8eed1380-9371-11e9-8bc4-901f11e9484f.png)
![Screenshot_20190620-153633](https://user-images.githubusercontent.com/38864617/59853642-94e2f480-9371-11e9-9cbe-1f16e91c4bbe.png)

</details>

<details>
<summary>What is the expected behavior?</summary>

1) The image is still wrong, it should be whole size. Seems the CSS didn't fix it (#49)
2) The boxes are all different size and some have overflow and aren't centered
</details>

<details>
<summary>Logs</summary>

None relevant

```

```

</details>

**Comment by imfunniee** [comment]
i have fixed that one in #49, its just that i'm not getting the time to publish a new version.

**Comment by Gelbpunkt** [comment]
I cloned the repo with #49 applied, the problem is with the current code

**Comment by imfunniee** [comment]
hmm, will look into that once i get some time. kinda busy

**Comment by imfunniee** [comment]
fixed in latest release, thank you for the contribution @Gelbpunkt 

btw i closed the PRs cause i wasn't able to give them much attention as i was busy with few other projects, sorry 😞
