### ISSUE TITLE
Ignore repository form command line `gitfolio build satishbabariya --ignore pages,satishbabariya.github.io`

### ISSUE THREAD

**Issue by satishbabariya** [imfunniee/gitfolio#82]
# What feature should be added?

Ignore repository from command line

 ```bash
gitfolio build satishbabariya --ignore pages,satishbabariya.github.io
```

# Why should this feature be added?
 to ignore repository which user don't want to add to its folio.

**Comment by imfunniee** [comment]
you can just delete them from your `index.html` file 😄
