### ISSUE TITLE
"unknown" Error

### ISSUE THREAD

**Issue by Spacella** [imfunniee/gitfolio#86]
<details>
<summary>System Information</summary>

| Name            | Value                                                          |
| --------------- | -------------------------------------------------------------- |
| OS              | Mac/**_Windows_**/Linux                                              |
| Node Version    |  v10.16.0                           |
| Project Version |  fatal: not a git repository (or any of the parent directories): .git|

</details>

<details>
<summary>What is the current behavior?</summary>

When `gitfolio run` is run in cmd it does this: http://spacella.xyz/images/i/i977r.png
</details>

<details>
<summary>What is the expected behavior?</summary>

It should run the gitfolio.
</details>

<details>
<summary>Logs</summary>

```

```

</details>

**Comment by imfunniee** [comment]
Hey,

Can't really tell anything from that image, but it looks like the ``x-default-browser`` package is not able to find your default browser, i might just remove it and prompt user to open the website on port 3000.

try opening http://localhost:3000 it might run

**Comment by Hardik500** [comment]
I think the issue is on windows system. 
Since I got the same error and when I tried it by opening [http://localhost:3000](http://localhost:3000) 
I got the error "Error: ENOENT: no such file or directory, stat 'C:\index.html' "
So the problem is that it is not able to find that folder which contains the file.

**Comment by imfunniee** [comment]
ah, i guess @Spacella tried running it before build command
