### ISSUE TITLE
Online service

### ISSUE THREAD

**Issue by lucasvazq** [imfunniee/gitfolio#89]
Can add online service through your website?
I mean something like this:
`https://imfunniee.github.io/u/{username}`
I like the template and I think you can redirect traffic to your website doing that

**Comment by imfunniee** [comment]
maybe in future, but rn it dont feel like working on it.

gonna close this one for now.

**Comment by WangNingkai** [comment]
@lucasvazq https://github.com/wangningkai/gitfolio-online You can try this

**Comment by lucasvazq** [comment]
@WangNingkai 🙏
