### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by batessmart** [imfunniee/gitfolio#90]
Hey,

When I try create new blog post I notice I get the following error

TypeError: Cannot read property 'split' of undefined

Could you please advise any requirements i need.

Thanks in advanced.

**Comment by stephenajulu** [comment]
I am having the same issue plus some blogs come out blank. Kindly help.

**Comment by sensui7** [comment]
@batessmart and @stephenajulu , you have to include the background image at the top right. Otherwise, the element is null, and you get the `undefined` error.

There should be a test case, and a conditional check for this...

**Comment by batessmart** [comment]
@sensui7  Yes that has fixed it,  Thanks!

**Comment by mmbatha** [comment]
@sensui7 Please explain... This error occurs within the ui.js file of the gitfolio npm package `TypeError: Cannot read property 'split' of undefined
    at /<user directory>/.brew/lib/node_modules/gitfolio/ui.js:71:35`
