### ISSUE TITLE
Social media integration to import data

### ISSUE THREAD

**Issue by sankarshanarao** [imfunniee/gitfolio#91]
# What feature should be added?

This feature adds Twitter, Linkedin and Medium links to your profile and imports professional(employers, projects) and social information from there.

# Why should this feature be added?

Since a portfolio is being made, adding these links help improve the profile better and also adds employer info

**Comment by 1RedOne** [comment]
I understand social links out, but how do we know what to injest from social media profiles?

**Comment by imfunniee** [comment]
ikr, social links are already implemented. 

BUT what's "imports professional and social information"??

**Comment by sankarshanarao** [comment]
Social media integrations are things like former employers, projects, skills from LinkedIn for example. Some public posts available on Instagram, Facebook, etc can be added as a small slideshow.
