### ISSUE TITLE
Can't install gitfolio with 'npm i gitfolio -g' 

### ISSUE THREAD

**Issue by sunn-e** [imfunniee/gitfolio#92]
<details>
<summary>System Information</summary>

| Name            | Value                                                          |
| --------------- | -------------------------------------------------------------- |
| OS              |Linux                                              |
| Node Version    |           v12.10.0                 |
| Project Version |  |

</details>

<details>
<summary>What is the current behavior?</summary>

</details>
not installing
<details>
<summary>What is the expected behavior?</summary>
Should run

</details>
don't know
<details>
<summary>Logs</summary>

npm WARN checkPermissions Missing write access to /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/lib/node_modules'] {
npm ERR!   stack: "Error: EACCES: permission denied, access '/usr/lib/node_modules'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/l/.npm/_logs/2019-09-15T06_42_52_805Z-debug.log

</details>

**Comment by imfunniee** [comment]
you are missing permissions on your device https://flaviocopes.com/npm-fix-missing-write-access-error/
